### ISSUE TITLE
3월 31일 오늘의 할 일

### ISSUE THREAD

**Issue by JAYCODE-git** [JAYCODE-git/testRepo#1]
## 일정
- [x] `9:00` 선배 특강
- [ ] `13:00` 협업 특강

### Todo
- [x] 협업 특강 복습
- [ ] 선언적인 코드 작성법 숙지
- [ ] 주간 4ls 회고

**Comment by JAYCODE-git** [comment]
issue close 실습을 위해 close 합니다. :)

**Comment by JAYCODE-git** [comment]
~~~한 이슈 발생

**Comment by JAYCODE-git** [comment]
1. 작업자 태그 @JAYCODE-git 님 이거 확인해주세요 :)
2.https://github.com/JAYCODE-git/testRepo/commit/6a8881a5f66deb3b8e89a66bc407613fae71779f 코드를 보여줘야 할 때 바로 git 링크 마크다운 문법으로 첨부 가능해요.
